### ISSUE TITLE
Version is not shown when gh extension list

### ISSUE THREAD

**Issue by spanishkangaroo** [InditexTech/gh-sherpa#67]
### Detailed description

When I execute 

`gh extension list`

I get back

`NAME        REPO                   VERSION`
`gh sherpa   InditexTech/gh-sherpa  ad6753cb`

### Expected behaviour

Expected behaviour is to get back the extension version in a semVer format, in this case 1.1.0.

**Comment by hielfx** [comment]
@spanishkangaroo thanks! we will look into this issue. It seems it may be something related to the way we create the releases, as it seems it's returning the latest commit in master.

**Comment by hielfx** [comment]
@spanishkangaroo Hi! You can now update the sherpa extension (`gh extension upgrade sherpa`) and it should be fixed. Thanks!

**Comment by spanishkangaroo** [comment]
@hielfx thank, works like a charm!

Output when running `gh extension list`:
`gh sherpa   InditexTech/gh-sherpa  1.1.1`
