### ISSUE TITLE
Branch naming not working for types other than feature

### ISSUE THREAD

**Issue by lluisoh** [InditexTech/gh-sherpa#70]
### Detailed description

When we try to create a PR or branch and the cli prompts us to select the type of branch, if we select the type **other**, instead of prompting to select among the other types (bugfix, dependency, deprecation, etc), it jumps straight to branch naming and ends up using `"other"` as a prefix.

Check this video:

https://github.com/InditexTech/gh-sherpa/assets/155542567/02ab12d5-1495-4e55-9eb6-a0c0921ccf36

### Expected behaviour

When we select other in the type of branch prompt, it should offer other branch types allow the user to select among them. Like the following screenshot from a previous version of sherpa-cli:

![Screenshot 2024-03-20 at 12 16 11](https://github.com/InditexTech/gh-sherpa/assets/155542567/145d204b-44d9-4a7c-8aab-c129e72a13ba)

**Comment by hielfx** [comment]
Hi! Thanks for reporting this issue. We will review this behavior and address it.

**Comment by jorgegarciarey** [comment]
@lluisoh , we're going to release a new version in a few days with this fix and some additional features.
