### ISSUE TITLE
Branch Name Length Control Configurable

### ISSUE THREAD

**Issue by jgomeztac** [InditexTech/gh-sherpa#77]
### Motivation

The current branch naming validation, which combines the GitHub project name with the branch name, often leads to branch names being unnecessarily short, particularly when the project name is already lengthy. This limitation often limit the ability to put a descriptive name in the branch, making it difficult to adequately convey their purpose or content. To overcome this limitation, it is crucial to provide users with the flexibility to utilize a sufficient number of characters to accurately describe their branches.

### Proposed Solution
Implement a configurable variable that enables users to set the maximum length for branch names. This feature would offer users the flexibility to establish a suitable length, thereby ensuring they possess a satisfactory number of characters to precisely name their branches.

### Acceptance criteria

- [ ] Implementation of the configuration variable to define the maximum branch name length.
- [ ] Update the default configuration to include the current value as default.
- [ ] Update the configuration documentation to include this variable.

**Comment by jorgegarciarey** [comment]
@spanishkangaroo , we're going to release a new version in a few days with this feature
